library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("slice", "dplyr")
conflict_prefer("pluck", "purrr")
conflict_prefer("chisq.test", "stats")
conflict_prefer("fisher.test", "stats")
conflict_prefer("map", "purrr")
conflict_prefer("binomial", "greta")
conflict_prefer("poisson", "greta")
conflict_prefer("apply", "greta")
conflict_prefer("pull", "dplyr")
conflict_prefer("complete", "tidyr")
conflict_prefer("expand", "tidyr")
weighted_mean <- weighted.mean

library(bayesplot)
library(broom)
library(broom.mixed)
library(coda)
library(cowplot)
library(dplyr)
library(future.apply)
library(fs)
library(furrr)
library(ggforce)
library(glue)
library(ggplot2)
library(grid)
library(greta, warn.conflicts = FALSE)
library(greta.gp, warn.conflicts = FALSE)
library(grid)
library(here)
library(httr)
library(janitor)
library(jsonlite)
library(knitr)
library(lubridate)
library(lme4)
library(magrittr)
library(MASS)
library(mgcv)
library(patchwork)
library(purrr)
library(polite)
library(R6)
library(RColorBrewer)
library(RCurl)
library(readr)
library(readxl)
library(reticulate)
library(rmarkdown)
library(rjson)
library(rvest)
library(scales)
library(sf)
library(slider)
library(splines)
library(stats)
library(stringr)
library(tensorflow)
library(targets)
library(tarchetypes)
library(tibble)
library(tidyr)
library(tidyverse)
library(truncdist)
library(units)
library(vctrs)
